version: "3"

services:
  redis:
    image: "redis/redis-stack:latest"
    restart: "unless-stopped"
    ports:
      # redis
      - "6379:6379"
      # insight
      - "8001:8001"

    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

  janus:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file:
      - .env
